application: ytquote
version: 1
runtime: python
api_version: 1

handlers:
- url: /play(.*)
  script: ytquote.py
  
- url: /(.*)
  static_files : static/index.html
  upload: static/index.html